jobs:
  changelog:
    if: 'github.actor == ''dependabot[bot]''

      '
    needs:
    - macos-browser
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      uses: dangoslen/dependabot-changelog-helper@v3
      with:
        activationLabels: dependencies
        sort: alpha
    - continue-on-error: true
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Changelog
  changes:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      )\n"
    name: Build list of changed files
    outputs:
      cifile: ${{ steps.filter.outputs.cifile }}
      javafiles: ${{ steps.filter.outputs.javafiles }}
      webfiles: ${{ steps.filter.outputs.webfiles }}
    permissions:
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        ref: ${{ github.ref }}
    - continue-on-error: true
      id: prev_commit
      name: Get previous commit SHA
      run: echo "PREV_COMMIT_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v3
      with:
        base: ${{ env.PREV_COMMIT_SHA }}
        filters: "javafiles:\n  - 'src/**'\n  - 'pom.xml'\n  - 'UMS.launch'\n  - '*.xml'\n\
          webfiles:\n  - 'react-client/**'\ncifile:\n  - '.github/workflows/ci.yaml'\n"
  lint:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.cifile\
      \ == 'true'\n)\n"
    name: Lint
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      name: Run tests
      run: 'mvn verify -P linter -DdisableXmlReport=true -DskipTests

        '
  linux-focal:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.cifile\
      \ == 'true'\n)\n"
    name: Linux 20.04
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      id: cache-node-dependencies
      name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        key: node-dependencies-${{ hashFiles('yarn.lock') }}
        path: 'react-client/.yarn

          react-client/node

          react-client/node_modules

          '
    - continue-on-error: true
      name: Run tests
      run: 'sudo apt-get -y install libmms0

        wget --no-check-certificate https://mediaarea.net/download/binary/libzen0/0.4.41/libzen0v5_0.4.41-1_amd64.xUbuntu_20.04.deb

        sudo dpkg -i libzen0v5_0.4.41-1_amd64.xUbuntu_20.04.deb

        wget --no-check-certificate https://mediaarea.net/download/binary/libmediainfo0/23.10/libmediainfo0v5_23.10-1_amd64.xUbuntu_20.04.deb

        sudo dpkg -i libmediainfo0v5_23.10-1_amd64.xUbuntu_20.04.deb

        mvn verify -P testing -DdisableXmlReport=true

        '
  linux-jammy:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.cifile\
      \ == 'true'\n)\n"
    name: Linux 22.04
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      id: cache-node-dependencies
      name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        key: node-dependencies-${{ hashFiles('yarn.lock') }}
        path: 'react-client/.yarn

          react-client/node

          react-client/node_modules

          '
    - continue-on-error: true
      name: Run tests
      run: 'sudo apt-get -y install libmms0

        wget --no-check-certificate https://mediaarea.net/download/binary/libzen0/0.4.41/libzen0v5_0.4.41-1_amd64.xUbuntu_22.04.deb

        sudo dpkg -i libzen0v5_0.4.41-1_amd64.xUbuntu_22.04.deb

        wget --no-check-certificate https://mediaarea.net/download/binary/libmediainfo0/23.10/libmediainfo0v5_23.10-1_amd64.xUbuntu_22.04.deb

        sudo dpkg -i libmediainfo0v5_23.10-1_amd64.xUbuntu_22.04.deb

        mvn verify -P testing -DdisableXmlReport=true

        '
  macos:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.cifile\
      \ == 'true'\n)\n"
    name: macOS Java tests
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      id: cache-node-dependencies
      name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        key: node-dependencies-${{ hashFiles('yarn.lock') }}
        path: 'react-client/.yarn

          react-client/node

          react-client/node_modules

          '
    - continue-on-error: true
      name: Run Java tests (XCode ${{ matrix.xcode }})
      run: DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
        && mvn verify -P testing-macos
    strategy:
      matrix:
        xcode:
        - 9.4.1
        - latest
  macos-browser:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.webfiles\
      \ == 'true' ||\n  needs.changes.outputs.cifile == 'true'\n)\n"
    name: macOS web browser tests
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      id: cache-node-dependencies
      name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        key: node-dependencies-${{ hashFiles('yarn.lock') }}
        path: 'react-client/.yarn

          react-client/node

          react-client/node_modules

          '
    - continue-on-error: true
      name: Install dependencies
      run: yarn
      working-directory: ./react-client
    - continue-on-error: true
      name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: ./react-client
    - continue-on-error: true
      name: Prepare server for Playwright tests
      run: npm run test:prepareserver:macos
      working-directory: ./react-client
    - continue-on-error: true
      name: Run Playwright tests
      run: DEBUG=pw:webserver yarn playwright test
      working-directory: ./react-client
  windows-latest:
    if: "(\n  (github.event_name == 'push' && (github.actor == 'renovate[bot]' ||\
      \ github.ref_name == 'main')) ||\n  (github.event_name == 'pull_request')\n\
      ) && (\n  needs.changes.outputs.javafiles == 'true' ||\n  needs.changes.outputs.cifile\
      \ == 'true'\n)\n"
    name: Windows
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      id: cache-node-dependencies
      name: Cache Node dependencies
      uses: actions/cache@v4
      with:
        key: node-dependencies-${{ hashFiles('yarn.lock') }}
        path: 'react-client/.yarn

          react-client/node

          react-client/node_modules

          '
    - continue-on-error: true
      name: Run tests
      run: mvn verify -P testing-windows
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
