jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: print-user
      name: print user login name
      run: echo 'aa${{ github.event.pull_request.user.login }}aa'
    - continue-on-error: true
      id: check
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      name: check if prs are dirty
      uses: eps1lon/actions-label-merge-conflict@v3
      with:
        commentOnDirty: '@dependabot recreate'
        dirtyLabel: conflicting
        repoToken: ${{ secrets.AUTOMATION_TOKEN }}
name: PullRequestConflicting
on:
  repository_dispatch:
    types: trigger-ga___pull-request-conflict.yaml
